// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// UI
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_SUCCESS = "SET_SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING = "STOP_LOADING";

// User
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const SET_SEARCHED_USER = "SET_SEARCHED_USER";
export const SET_ALL_USERS = "SET_ALL_USERS";
export const LOADING_USER = "LOADING_USER";
export const SET_PERFORMANCES = "SET_PERFORMANCES";

// Data
export const SET_PROJECT = "SET_PROJECT";
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECT_MEMBERS = "SET_PROJECT_MEMBERS";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const SET_TODOS = "SET_TODOS";
export const SET_TODO = "SET_TODO";
export const REMOVE_TODO = "REMOVE_TODO";

// Chat Toxicity
export const SET_CHAT_TOXICITY = "SET_CHAT_TOXICITY";
export const REMOVE_CHAT_TOXICITY = "REMOVE_CHAT_TOXICITY";
export const SET_CHAT_TOXICITIES = "SET_CHAT_TOXICITIES";
